base functionality added
dmkalash/afina pull request #1
Opened 2021-02-13 16:23 UTC by dmkalash

Version 1

2021-02-16 10:03 UTC, xphoenix commented on src/storage/SimpleLRU.cpp
> +          return PutIfAbsent(key, value);
Это тоже будет ```find```

2021-02-16 10:04 UTC, xphoenix reviewed
```
Put() {
   auto it = find(key);
   if (it == end()) {
       return _insert_new_node(key, value);
   }
   _update_node_content(it, new_value);
   return move_to_head(it);   
}

Set() {
   auto it = find(key);
   if (it == end()) {
       return false;
   }
   _update_node_content(it, new_value);
   return move_to_head(it);   
}
```

2021-02-27 18:02 UTC, Fen99 requested changes

2021-02-27 18:02 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +      auto it_find = _lru_index.find(std::cref(key));
Если key.size() + value.size() > max_size, то даже find() не нужен

2021-02-27 18:02 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +      if (_overflow(_cur_size + node_size)) {
Лишний if

2021-02-27 18:02 UTC, Fen99 commented on src/storage/SimpleLRU.cpp
> +      node_ref.get().value = value;
Сначала очистка, потом установка.
Чтобы избежать проблем с удалением it_find - сначала переместить его в голову

2021-04-03 18:28 UTC, Fen99 approved these changes
По https://github.com/dmkalash/afina/pull/3

2021-06-03 17:29 UTC, merged